"""initial

Revision ID: 68d46dab0a59
Revises: 
Create Date: 2026-06-24 22:38:48.878158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d46dab0a59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS auth_ext")
    op.execute("CREATE SCHEMA IF NOT EXISTS med")
    op.execute("CREATE SCHEMA IF NOT EXISTS care")
    op.execute("CREATE SCHEMA IF NOT EXISTS rx")
    op.execute("CREATE SCHEMA IF NOT EXISTS safety")
    op.execute("CREATE SCHEMA IF NOT EXISTS ocr")
    op.execute("CREATE SCHEMA IF NOT EXISTS sched")
    op.execute("CREATE SCHEMA IF NOT EXISTS remind")

    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('allergies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('chronic_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('patient', 'caregiver', 'admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id'),
    schema='auth_ext'
    )
    op.create_table('medicines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('drug_class', sa.String(length=100), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_otc', sa.Boolean(), nullable=False),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='med'
    )
    op.create_table('caregiver_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='care'
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('prescribed_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'expired', 'revoked', 'draft')", name='ck_prescription_status'),
    sa.ForeignKeyConstraint(['caregiver_id'], ['auth_ext.user_profiles.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rx'
    )
    op.create_table('drug_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medicine_a_id', sa.UUID(), nullable=False),
    sa.Column('medicine_b_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('clinical_effect', sa.Text(), nullable=True),
    sa.Column('management', sa.Text(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('major', 'moderate', 'minor')", name='ck_drug_interaction_severity'),
    sa.CheckConstraint('medicine_a_id < medicine_b_id', name='ck_drug_interaction_order'),
    sa.ForeignKeyConstraint(['medicine_a_id'], ['med.medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_b_id'], ['med.medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_a_id', 'medicine_b_id', name='uq_drug_interaction_pair'),
    schema='safety'
    )
    op.create_table('prescription_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['rx.prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rx'
    )
    op.create_table('prescription_medicines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('refills', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['med.medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['rx.prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rx'
    )
    op.create_table('ocr_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_image_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('engine_used', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_image_id'], ['rx.prescription_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ocr'
    )
    op.create_table('medicine_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_medicine_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('schedule_name', sa.String(length=100), nullable=False),
    sa.Column('recurrence_type', sa.String(length=20), nullable=False),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('dose_time', sa.Time(), nullable=True),
    sa.Column('dose_amount', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_medicine_id'], ['rx.prescription_medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sched'
    )
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medicine_schedule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent', 'acknowledged', 'missed', 'skipped', 'snoozed')", name='ck_reminder_status'),
    sa.ForeignKeyConstraint(['medicine_schedule_id'], ['sched.medicine_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='remind'
    )
    op.create_table('dose_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medicine_schedule_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('taken', 'missed', 'skipped')", name='ck_dose_log_action'),
    sa.ForeignKeyConstraint(['medicine_schedule_id'], ['sched.medicine_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['remind.reminders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='remind'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dose_logs', schema='remind')
    op.drop_table('reminders', schema='remind')
    op.drop_table('medicine_schedules', schema='sched')
    op.drop_table('ocr_jobs', schema='ocr')
    op.drop_table('prescription_medicines', schema='rx')
    op.drop_table('prescription_images', schema='rx')
    op.drop_table('drug_interactions', schema='safety')
    op.drop_table('prescriptions', schema='rx')
    op.drop_table('caregiver_relationships', schema='care')
    op.drop_table('medicines', schema='med')
    op.drop_table('user_profiles', schema='auth_ext')
    # ### end Alembic commands ###
