"""Update PrescriptionImage and ReminderLog models

Revision ID: 05847b7c6539
Revises: 3b3b5355838a
Create Date: 2026-06-27 13:07:44.306183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05847b7c6539'
down_revision: Union[str, Sequence[str], None] = '3b3b5355838a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_token_blocklist_jti'), table_name='token_blocklist', schema='auth_ext')
    op.drop_constraint(op.f('token_blocklist_jti_key'), 'token_blocklist', schema='auth_ext', type_='unique')
    op.create_index(op.f('ix_auth_ext_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=True, schema='auth_ext')
    op.alter_column('prescription_images', 'file_path', new_column_name='public_url', schema='rx')
    op.add_column('prescription_images', sa.Column('storage_path', sa.Text(), nullable=True), schema='rx')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescription_images', 'public_url', new_column_name='file_path', schema='rx')
    op.drop_column('prescription_images', 'storage_path', schema='rx')
    op.drop_index(op.f('ix_auth_ext_token_blocklist_jti'), table_name='token_blocklist', schema='auth_ext')
    op.create_unique_constraint(op.f('token_blocklist_jti_key'), 'token_blocklist', ['jti'], schema='auth_ext', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=False, schema='auth_ext')
    # ### end Alembic commands ###
