"""add_missing_tables

Revision ID: 3b3b5355838a
Revises: 68d46dab0a59
Create Date: 2026-06-27 12:11:31.810888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b3b5355838a'
down_revision: Union[str, Sequence[str], None] = '68d46dab0a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='care'
    )
    op.create_table('drug_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medicine_a_id', sa.UUID(), nullable=False),
    sa.Column('medicine_b_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('clinical_effect', sa.Text(), nullable=True),
    sa.Column('management', sa.Text(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('major', 'moderate', 'minor')", name='ck_drug_interaction_severity'),
    sa.CheckConstraint('medicine_a_id < medicine_b_id', name='ck_drug_interaction_order'),
    sa.ForeignKeyConstraint(['medicine_a_id'], ['med.medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_b_id'], ['med.medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_a_id', 'medicine_b_id', name='uq_drug_interaction_pair'),
    schema='safety'
    )
    op.create_table('prescription_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['rx.prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rx'
    )
    op.create_table('prescription_medicines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('refills', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['med.medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['rx.prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rx'
    )
    op.create_table('ocr_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_image_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('engine_used', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_image_id'], ['rx.prescription_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ocr'
    )
    op.create_table('medicine_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_medicine_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('schedule_name', sa.String(length=100), nullable=False),
    sa.Column('recurrence_type', sa.String(length=20), nullable=False),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('dose_time', sa.Time(), nullable=True),
    sa.Column('dose_amount', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_medicine_id'], ['rx.prescription_medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sched'
    )
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medicine_schedule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent', 'acknowledged', 'missed', 'skipped', 'snoozed')", name='ck_reminder_status'),
    sa.ForeignKeyConstraint(['medicine_schedule_id'], ['sched.medicine_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='remind'
    )
    op.create_table('dose_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medicine_schedule_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('taken', 'missed', 'skipped')", name='ck_dose_log_action'),
    sa.ForeignKeyConstraint(['medicine_schedule_id'], ['sched.medicine_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['remind.reminders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_ext.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='remind'
    )
    # NOTE: Leaving legacy tables (med.medicine_aliases, i18n.*) untouched — they
    # were created by schema.sql and are not part of our ORM models.
    op.add_column('user_profiles', sa.Column('hashed_password', sa.String(length=255), nullable=True), schema='auth_ext')
    op.alter_column('user_profiles', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='auth_ext')
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               schema='auth_ext')
    op.alter_column('user_profiles', 'locale',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'en'::text"),
               schema='auth_ext')
    op.alter_column('user_profiles', 'role',
               existing_type=postgresql.ENUM('patient', 'caregiver', 'admin', name='user_role'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'patient'::user_role"),
               schema='auth_ext')
    op.alter_column('user_profiles', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='gender_type'),
               type_=sa.String(length=20),
               existing_nullable=True,
               schema='auth_ext')
    op.alter_column('user_profiles', 'blood_group',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               schema='auth_ext')
    op.alter_column('user_profiles', 'allergies',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=True,
               comment=None,
               existing_comment='Array of known allergen names or ICD-10 codes.',
               existing_server_default=sa.text("'{}'::text[]"),
               schema='auth_ext')
    op.alter_column('user_profiles', 'chronic_conditions',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=True,
               comment=None,
               existing_comment='Array of chronic condition labels or ICD-10 codes.',
               existing_server_default=sa.text("'{}'::text[]"),
               schema='auth_ext')
    op.create_unique_constraint(None, 'user_profiles', ['phone'], schema='auth_ext')
    # NOTE: drop_table_comment skipped — not needed for functionality.
    op.alter_column('medicines', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               schema='med')
    op.alter_column('medicines', 'generic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True,
               schema='med')
    op.alter_column('medicines', 'brand_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'manufacturer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'drug_class',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'form',
               existing_type=postgresql.ENUM('tablet', 'capsule', 'syrup', 'injection', 'patch', 'inhaler', 'drops', 'cream', 'powder', 'gel', 'suppository', 'other', name='medicine_form'),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'strength',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'is_controlled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE if this is a scheduled/controlled substance.',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='med')
    op.drop_table_comment(
        'medicines',
        existing_comment='Canonical, deduplicated medicine catalog (shared across all users).',
        schema='med'
    )
    op.alter_column('prescriptions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='rx')
    op.alter_column('prescriptions', 'doctor_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='rx')
    op.alter_column('prescriptions', 'hospital_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='rx')
    op.alter_column('prescriptions', 'status',
               existing_type=postgresql.ENUM('active', 'expired', 'archived', name='prescription_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::prescription_status"),
               schema='rx')
    op.create_foreign_key(None, 'prescriptions', 'user_profiles', ['user_id'], ['user_id'], source_schema='rx', referent_schema='auth_ext', ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'user_profiles', ['caregiver_id'], ['user_id'], source_schema='rx', referent_schema='auth_ext', ondelete='SET NULL')
    op.drop_table_comment(
        'prescriptions',
        existing_comment='Top-level prescription records belonging to a patient.',
        schema='rx'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'prescriptions',
        'Top-level prescription records belonging to a patient.',
        existing_comment=None,
        schema='rx'
    )
    op.drop_constraint(None, 'prescriptions', schema='rx', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', schema='rx', type_='foreignkey')
    op.alter_column('prescriptions', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('active', 'expired', 'archived', name='prescription_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::prescription_status"),
               schema='rx')
    op.alter_column('prescriptions', 'hospital_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='rx')
    op.alter_column('prescriptions', 'doctor_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='rx')
    op.alter_column('prescriptions', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='rx')
    op.create_table_comment(
        'medicines',
        'Canonical, deduplicated medicine catalog (shared across all users).',
        existing_comment=None,
        schema='med'
    )
    op.alter_column('medicines', 'is_controlled',
               existing_type=sa.BOOLEAN(),
               comment='TRUE if this is a scheduled/controlled substance.',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='med')
    op.alter_column('medicines', 'unit',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'strength',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'form',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('tablet', 'capsule', 'syrup', 'injection', 'patch', 'inhaler', 'drops', 'cream', 'powder', 'gel', 'suppository', 'other', name='medicine_form'),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'drug_class',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'manufacturer',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'brand_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='med')
    op.alter_column('medicines', 'generic_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False,
               schema='med')
    op.alter_column('medicines', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='med')
    op.create_table_comment(
        'user_profiles',
        'Extended profile data for Supabase auth users.',
        existing_comment=None,
        schema='auth_ext'
    )
    op.drop_constraint(None, 'user_profiles', schema='auth_ext', type_='unique')
    op.alter_column('user_profiles', 'chronic_conditions',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               comment='Array of chronic condition labels or ICD-10 codes.',
               existing_server_default=sa.text("'{}'::text[]"),
               schema='auth_ext')
    op.alter_column('user_profiles', 'allergies',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               comment='Array of known allergen names or ICD-10 codes.',
               existing_server_default=sa.text("'{}'::text[]"),
               schema='auth_ext')
    op.alter_column('user_profiles', 'blood_group',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='auth_ext')
    op.alter_column('user_profiles', 'gender',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='gender_type'),
               existing_nullable=True,
               schema='auth_ext')
    op.alter_column('user_profiles', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('patient', 'caregiver', 'admin', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'patient'::user_role"),
               schema='auth_ext')
    op.alter_column('user_profiles', 'locale',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'en'::text"),
               schema='auth_ext')
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='auth_ext')
    op.alter_column('user_profiles', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='auth_ext')
    op.drop_column('user_profiles', 'hashed_password', schema='auth_ext')
    op.create_table('medicine_explanations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usage_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('side_effects', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precautions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('storage_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='TRUE if explanation has been reviewed by a medical professional.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['i18n.languages.id'], name=op.f('medicine_explanations_language_id_fkey')),
    sa.ForeignKeyConstraint(['medicine_id'], ['med.medicines.id'], name=op.f('medicine_explanations_medicine_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('medicine_explanations_pkey')),
    sa.UniqueConstraint('medicine_id', 'language_id', name=op.f('uq_medicine_explanation_lang'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='i18n'
    )
    op.create_table('languages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('script', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.CheckConstraint("code ~ '^[a-z]{2,3}(-[A-Z]{2,4})?$'::text", name=op.f('chk_language_code_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('languages_pkey')),
    sa.UniqueConstraint('code', name=op.f('languages_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='i18n',
    comment='Supported BCP-47 language codes for multilingual content.'
    )
    op.create_table('medicine_aliases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.TEXT(), server_default=sa.text("'en'::text"), autoincrement=False, nullable=False),
    sa.CheckConstraint("TRIM(BOTH FROM alias) <> ''::text", name=op.f('chk_alias_notempty')),
    sa.ForeignKeyConstraint(['medicine_id'], ['med.medicines.id'], name=op.f('medicine_aliases_medicine_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('medicine_aliases_pkey')),
    sa.UniqueConstraint('medicine_id', 'alias', 'locale', name=op.f('uq_medicine_alias_locale'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='med',
    comment='Alternative names, spellings, and locale-specific aliases for medicines.'
    )
    op.drop_table('dose_logs', schema='remind')
    op.drop_table('reminders', schema='remind')
    op.drop_table('medicine_schedules', schema='sched')
    op.drop_table('ocr_jobs', schema='ocr')
    op.drop_table('prescription_medicines', schema='rx')
    op.drop_table('prescription_images', schema='rx')
    op.drop_table('drug_interactions', schema='safety')
    op.drop_table('caregiver_relationships', schema='care')
    # ### end Alembic commands ###
